spring:

  profiles:
    include: mysql

  batch:
    jdbc:
      initialize-schema: always # Default
    #      table-prefix: SYSTEM
    job:
      enabled: true # Disable auto-start of Job
      names: ${job.name:NONE}


