spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/batch?useUnicode=true&characterEncoding=utf8
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver